name: ROS 2 Jazzy CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  industrial_ci:
    name: Jazzy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: jazzy
          ROS_REPO: main
          TARGET_WORKSPACE: speech_recognition_msgs
